modLoader="javafml"
loaderVersion="[40,)"
license="BSD"

[[mods]]
modId="exhibition_toolkit"
version="${file.jarVersion}"
displayName="Exhibition Toolkit"
authors="TeaConMC, 3TUSK"
description="Useful things in in-game convention"

[[dependencies.exhibition_toolkit]]
modId="forge"
mandatory=true
versionRange="[40,)"
ordering="NONE"
side="BOTH"

[[dependencies.exhibition_toolkit]]
modId="minecraft"
mandatory=true
versionRange="[1.18,)"
ordering="NONE"
side="BOTH"

